export interface Question {
  id: string
  question: string
  options: string[]
  correctAnswer: number
  funFact?: string
}

export interface Category {
  id: string
  name: string
  emoji: string
  description: string
  color: string
  questions: Question[]
}

export const categories: Category[] = [
  {
    id: "animals",
    name: "Wacky Animals",
    emoji: "🦄",
    description: "Bizarre facts about our furry (and not-so-furry) friends!",
    color: "from-green-400 to-blue-500",
    questions: [
      {
        id: "a1",
        question: "Three of these animals hibernate. Which one does not?",
        options: ["Mouse", "Sloth", "Frog", "Snake"],
        correctAnswer: 1,
        funFact: "Sloths don't hibernate - they're just naturally slow and sleepy all year round!",
      },
      {
        id: "a2",
        question: "All of these animals are omnivorous except one.",
        options: ["Fox", "Mouse", "Opossum", "Snail"],
        correctAnswer: 3,
        funFact: "Snails are herbivores - they stick to plants and algae for their meals!",
      },
      {
        id: "a3",
        question: "Three of these Latin names are names of bears. Which is the odd one?",
        options: ["Melursus ursinus", "Helarctos malayanus", "Ursus minimus", "Felis silvestris catus"],
        correctAnswer: 3,
        funFact: "Felis silvestris catus is actually the scientific name for the domestic cat!",
      },
      {
        id: "a4",
        question: "These are typical Australian animals except one.",
        options: ["Platypus", "Dingo", "Echidna", "Sloth"],
        correctAnswer: 3,
        funFact: "Sloths are native to Central and South America, not Australia!",
      },
      {
        id: "a5",
        question: "Representatives of three of these species produce venom of their own. Which is the odd species?",
        options: ["Lizards", "Scorpions", "Frogs", "Mosquitos"],
        correctAnswer: 3,
        funFact: "Mosquitos don't produce venom - they inject saliva to prevent blood clotting!",
      },
      {
        id: "a6",
        question: "Three of these species shed their skin. Which one does not?",
        options: ["Penguins", "Snakes", "Insects", "Crustaceans"],
        correctAnswer: 0,
        funFact: "Penguins molt their feathers but don't shed their skin like reptiles and arthropods!",
      },
      {
        id: "a7",
        question: "All dogs, cats and birds are colorblind.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact:
          "Many animals can see colors, though differently than humans. Birds especially have excellent color vision!",
      },
      {
        id: "a8",
        question: "All of these animals have large ears (relative to their size) except one.",
        options: ["Polar bears", "Foxes", "Bats", "Elephants"],
        correctAnswer: 0,
        funFact: "Polar bears have small ears to minimize heat loss in the Arctic!",
      },
      {
        id: "a9",
        question: "This percentage of all snakes on Earth are lethal to humans.",
        options: ["10%", "20%", "15%", "25%"],
        correctAnswer: 2,
        funFact: "Only about 15% of snakes are dangerous to humans - most are harmless!",
      },
      {
        id: "a10",
        question: "Snakes are this kind of animals.",
        options: ["Herbivorous", "Omnivorous", "Carnivorous", "Vegetarian"],
        correctAnswer: 2,
        funFact: "All snakes are carnivores - they only eat other animals!",
      },
      {
        id: "a11",
        question: "Snakes consume their food by means of this process.",
        options: ["Breathing", "Absorption", "Swallowing", "Chewing"],
        correctAnswer: 2,
        funFact: "Snakes swallow their prey whole since they can't chew!",
      },
      {
        id: "a12",
        question: "Snakes reproduce only by laying eggs.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "Some snakes give birth to live young instead of laying eggs!",
      },
      {
        id: "a13",
        question: "Snakes are deaf.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Snakes don't have external ears but can sense vibrations through their bodies!",
      },
      {
        id: "a14",
        question: "Snake skin is covered in scales.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Snake scales are made of keratin, the same material as human fingernails!",
      },
      {
        id: "a15",
        question: "Snakes belong to the following category.",
        options: ["Invertebrates", "Lizards", "Reptiles", "Mammals"],
        correctAnswer: 2,
        funFact: "Snakes are reptiles, closely related to lizards!",
      },
      {
        id: "a16",
        question: "A specialist in snakes is called one of these.",
        options: ["Pisciculturist", "Ornithologist", "Ophiologist", "Herpetologist"],
        correctAnswer: 2,
        funFact:
          "An ophiologist specifically studies snakes, while a herpetologist studies all reptiles and amphibians!",
      },
      {
        id: "a17",
        question: "One of the following snakes does not belong to the Viperidae family.",
        options: ["Horned adder", "Grass snake", "Viper", "Asp"],
        correctAnswer: 1,
        funFact: "Grass snakes are harmless colubrids, not venomous vipers!",
      },
      {
        id: "a18",
        question: "Snakes are very likely to attack us, regardless of whether they feel threatened or not.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "Snakes are generally shy and only attack when they feel threatened!",
      },
      {
        id: "a19",
        question:
          "Cobras are venomous snakes of family Elapidae, that generally inhabit regions of these two continents.",
        options: ["South America and Asia", "Asia and Africa", "Asia and Australia", "South America and Australia"],
        correctAnswer: 1,
        funFact: "Cobras are found throughout Asia and Africa in various habitats!",
      },
      {
        id: "a20",
        question:
          "The cobra's most recognizable feature is its hood, a flap of skin and muscle behind the head, believed to serve this purpose.",
        options: ["Balance control", "Heat collection from sun rays", "Camouflage", "More threatening appearance"],
        correctAnswer: 3,
        funFact: "The cobra's hood makes it look larger and more intimidating to predators and threats!",
      },
      {
        id: "a21",
        question:
          "The Cobra is at the top of the food chain, with only two main predators -- one is man and the other is this animal.",
        options: ["Jackal", "Mongoose", "Lynx", "Eagle"],
        correctAnswer: 1,
        funFact: "Mongooses are famous for their ability to fight and kill cobras!",
      },
      {
        id: "a22",
        question: "This is where the Cobra's ribs are situated.",
        options: [
          "Behind its head",
          "In its chest, around the middle of the body",
          "Cobras have no ribs",
          "In its tale",
        ],
        correctAnswer: 0,
        funFact: "Cobra ribs extend from behind the head, which is what allows them to spread their hood!",
      },
      {
        id: "a23",
        question: "The King Cobra feeds almost exclusively on other snakes, even toxic ones.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "King Cobras are ophiophagous - they primarily eat other snakes, including venomous ones!",
      },
      {
        id: "a24",
        question: "A baby cobra is fully able to defend itself in as little as this many hours after being born.",
        options: ["3", "12", "48", "72"],
        correctAnswer: 0,
        funFact: "Baby cobras are born with fully functional venom and can defend themselves immediately!",
      },
      {
        id: "a25",
        question:
          "What type of dog did Richard Nixon receive from a Texan while he was a candidate for Vice President?",
        options: ["German Shepherd", "Cocker Spaniel", "Golden Retriever", "Welsh Corgy"],
        correctAnswer: 1,
        funFact: "Nixon's famous 'Checkers' speech was about keeping his Cocker Spaniel!",
      },
      {
        id: "a26",
        question: "What was the name of Socks' companion at the White House during the Clinton Administration?",
        options: ["Buddy", "Shoes", "Bailey", "Buster"],
        correctAnswer: 0,
        funFact: "Buddy was a chocolate Labrador Retriever who joined Socks the cat at the White House!",
      },
      {
        id: "a27",
        question: "President Ford's dog was named Freedom.",
        options: ["False", "True"],
        correctAnswer: 0,
        funFact: "President Ford's dog was actually named Liberty, not Freedom!",
      },
      {
        id: "a28",
        question: "Which of these Presidents had the most pets?",
        options: ["Franklin Delano Roosevelt", "Theodore Roosevelt", "Bill Clinton", "Woodrow Wilson"],
        correctAnswer: 1,
        funFact:
          "Theodore Roosevelt had an amazing menagerie including dogs, cats, guinea pigs, a badger, and even a bear!",
      },
      {
        id: "a29",
        question: "What breed is known as the favourite breed of Queen Elizabeth II?",
        options: ["Border Collie", "Old English Sheepdog", "Welsh Corgi", "Australian Cattle Dog"],
        correctAnswer: 2,
        funFact: "Queen Elizabeth II has owned more than 30 Corgis during her reign!",
      },
      {
        id: "a30",
        question: "What was the name of Frasier's father's dog on the hit TV show set in Seattle?",
        options: ["Niles", "Marty", "Eddie", "Skip"],
        correctAnswer: 2,
        funFact: "Eddie was a Jack Russell Terrier who often stole scenes on Frasier!",
      },
      {
        id: "a31",
        question: "Which one of these sea mammals is not in the endangered species lists?",
        options: ["Fin Whale", "Pilot whale", "Blue Whale", "Humpback Whale"],
        correctAnswer: 1,
        funFact: "Pilot whales are relatively stable in population compared to the great whales!",
      },
      {
        id: "a32",
        question:
          "This endangered turtle is the biggest of all living turtles, reaching a length of over 2.7 m (8.8 ft) and weight of 900 kg (2,000 lb).",
        options: [
          "Leatherback Sea Turtle",
          "Kemp's Ridley Turtle",
          "Hawksbill Sea Turtle",
          "Mesoamerican River Turtle",
        ],
        correctAnswer: 0,
        funFact: "Leatherback Sea Turtles are not only the largest turtles but also the deepest diving!",
      },
      {
        id: "a33",
        question: "Name the rarest and most endangered of all wolves.",
        options: ["Red Wolf", "Ethiopian Wolf", "Black-backed Wolf", "Gray Wolf"],
        correctAnswer: 0,
        funFact: "Red Wolves are critically endangered with only about 20-25 individuals left in the wild!",
      },
      {
        id: "a34",
        question:
          "The endangered Komodo dragon is the largest living lizard in the world, growing to an average length of 2-3 meters (10 feet).",
        options: ["False", "True"],
        correctAnswer: 1,
        funFact: "Komodo dragons can grow up to 10 feet long and weigh over 150 pounds!",
      },
      {
        id: "a35",
        question:
          "This species of great apes with long arms and reddish hair suffer habitat destruction due to logging, mining and forest fires.",
        options: ["Gorilla", "Baboons", "Orangutan", "Chimpanzee"],
        correctAnswer: 2,
        funFact: "Orangutans are critically endangered due to palm oil plantations destroying their rainforest homes!",
      },
      {
        id: "a36",
        question:
          "What is the natural habitat of the snow leopard, that was hunted down for its beautiful fur, as a result of which its population went down to 1,000 animals in the 1960s?",
        options: ["North America", "Central Asia and North America", "Central Asia", "Europe and North America"],
        correctAnswer: 2,
        funFact:
          "Snow leopards live in the high mountains of Central Asia and are perfectly adapted to cold, rocky terrain!",
      },
      {
        id: "a37",
        question:
          "The Asian Elephant, the only living species of the genus Elephas, is the bigger relative of the African Elephant.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "African elephants are actually larger than Asian elephants!",
      },
      {
        id: "a38",
        question:
          "This freshwater mammal, found only in the Yangtze River, is the most endangered (even possibly extinct) cetacean and one of the most endangered species in the world.",
        options: ["Ganges River Dolphin", "Chinese River Dolphin", "La Plata Dolphin", "Amazon River Dolphin"],
        correctAnswer: 1,
        funFact: "The Chinese River Dolphin (Baiji) was declared functionally extinct in 2006 - a tragic loss!",
      },
      {
        id: "a39",
        question:
          "This small nocturnal animal, whose natural habitat are the deserts of Northern Africa, is known to jump not only for hunting or protection, but also for pleasure.",
        options: ["Cape Fox", "Red Fox", "Bengal Fox", "Fennec"],
        correctAnswer: 3,
        funFact: "Fennec foxes are the smallest foxes in the world and have huge ears to help them stay cool!",
      },
      {
        id: "a40",
        question:
          "Jack jumper ants, yellowish-orange carnivorous ants named after their characteristic jumpy motions, can be found only on which continent?",
        options: ["North America", "Australia", "Africa", "Asia"],
        correctAnswer: 1,
        funFact:
          "Jack jumper ants are found only in Australia and are known for their painful, potentially dangerous stings!",
      },
      {
        id: "a41",
        question:
          "This small, graceful member of the antelope family is an extraordinary jumper - while leaping, it touches the rocky terrain of its South African habitats only with the tip of its hooves, resembling a dance.",
        options: ["Oribi", "Roan Antelope", "Scimitar Oryx", "Klipspringer"],
        correctAnswer: 3,
        funFact: "Klipspringers can leap from rock to rock with incredible precision, like mountain ballet dancers!",
      },
      {
        id: "a42",
        question:
          "Although the jumping viper, a chiefly nocturnal snake, is one of the most powerful jumpers of the snake family, capable of rising up to 1 meter (3 feet) during a strike, its poison is not lethal to humans.",
        options: ["False", "True"],
        correctAnswer: 0,
        funFact: "The jumping viper's bite can actually be quite dangerous and potentially fatal to humans!",
      },
      {
        id: "a43",
        question: "Zoophobia is the fear of animals.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Zoophobia is indeed the irrational fear of animals - it can range from mild to severe!",
      },
      {
        id: "a44",
        question: "The hummingbird is the world's smallest bird.",
        options: ["False", "True"],
        correctAnswer: 1,
        funFact: "The Bee Hummingbird is the world's smallest bird, weighing less than a penny!",
      },
      {
        id: "a45",
        question: "Which of these animals swims the fastest?",
        options: ["Flounder", "Shark", "Dolphin", "Jellyfish"],
        correctAnswer: 2,
        funFact: "Dolphins can reach speeds of up to 35 mph in the water!",
      },
      {
        id: "a46",
        question: "Which word refers to the sound peacocks make?",
        options: ["Scream", "Squill", "Squeak", "Squall"],
        correctAnswer: 0,
        funFact: "Peacocks make loud screaming calls that can be heard from over a mile away!",
      },
      {
        id: "a47",
        question: "Ancient Japanese thought this animal caused earthquakes.",
        options: ["Birds", "Spiders", "Snakes", "Frogs"],
        correctAnswer: 1,
        funFact: "In Japanese mythology, a giant spider or catfish was believed to cause earthquakes!",
      },
      {
        id: "a48",
        question: "How many types of bats are there?",
        options: ["900", "700", "500", "200"],
        correctAnswer: 0,
        funFact: "There are about 900 species of bats - that's nearly 20% of all mammal species!",
      },
      {
        id: "a49",
        question: "Chocolate cannot kill a dog.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "Chocolate contains theobromine which is toxic to dogs and can be fatal!",
      },
      {
        id: "a50",
        question: "This animal can clean its own ears with its 21-inch tongue.",
        options: ["Lizard", "Elephant", "Lion", "Giraffe"],
        correctAnswer: 3,
        funFact: "Giraffes have incredibly long tongues that help them reach high leaves and keep clean!",
      },
      {
        id: "a51",
        question:
          "It has been estimated that in Australia, there are about twice as many kangaroos as there are people.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Australia has an estimated 50 million kangaroos compared to about 25 million people!",
      },
      {
        id: "a52",
        question: "What is the fastest animal on 6 legs?",
        options: ["Ladybug", "Cockroach", "Beetle", "Ant"],
        correctAnswer: 1,
        funFact: "Cockroaches can run up to 3 mph - pretty impressive for such tiny legs!",
      },
      {
        id: "a53",
        question: "Sheep are similar to cows in that they have a stomach which contains four chambers.",
        options: ["False", "True"],
        correctAnswer: 1,
        funFact: "Both sheep and cows are ruminants with four-chambered stomachs for digesting grass!",
      },
      {
        id: "a54",
        question: "What is a female sheep called or known as?",
        options: ["ewe", "colt", "fleece", "ram"],
        correctAnswer: 0,
        funFact: "A female sheep is called a ewe, while a male is called a ram!",
      },
      {
        id: "a55",
        question: "What is the white tiger's scientific name?",
        options: ["Pantha", "Panthera tigis", "Panthera tiger", "Panthera tigris"],
        correctAnswer: 3,
        funFact: "White tigers are just a color variant of regular tigers (Panthera tigris) with a genetic condition!",
      },
      {
        id: "a56",
        question: "Can tigers live to be 20 years old?",
        options: ["Yes", "No"],
        correctAnswer: 0,
        funFact: "Tigers can live 20-25 years in captivity, though wild tigers typically live 10-15 years!",
      },
      {
        id: "a57",
        question: "All tigers have stripes.",
        options: ["False", "True"],
        correctAnswer: 0,
        funFact: "Some tigers are born without stripes due to genetic mutations, though this is extremely rare!",
      },
      {
        id: "a58",
        question: "Which of the following is not a type of chipmunk?",
        options: ["Bushy-tailed", "Long-eared", "Eastern", "Sonoma"],
        correctAnswer: 0,
        funFact: "There's no such thing as a 'Bushy-tailed' chipmunk - that's made up!",
      },
      {
        id: "a59",
        question: "Which of these is not an actual breed of horse?",
        options: ["Sioux", "Russian Trotter", "Belgian", "Murgese"],
        correctAnswer: 0,
        funFact: "Sioux is a Native American tribe, not a horse breed!",
      },
      {
        id: "a60",
        question: "Which of the following is not a breed of dog?",
        options: ["Pom-a-poo", "Lakeland terrier", "Fox terrier", "Ferret terrier"],
        correctAnswer: 3,
        funFact: "There's no such thing as a 'Ferret terrier' - ferrets aren't even dogs!",
      },
      {
        id: "a61",
        question: "One of these is not a true breed of cat. Which one?",
        options: ["Pixie-bob", "Maine coon", "Ragdoll", "French Twist"],
        correctAnswer: 3,
        funFact: "French Twist is a hairstyle, not a cat breed!",
      },
      {
        id: "a62",
        question: "Which of these is not a type of beetle?",
        options: ["Long-horn beetle", "Stag beetle", "Flea beetle", "Burrowing beetle"],
        correctAnswer: 3,
        funFact: "While beetles do burrow, 'Burrowing beetle' isn't a specific type!",
      },
      {
        id: "a63",
        question: "Which of the following is not a type of spider?",
        options: ["Glass spider", "Trapdoor spider", "Brown recluse spider", "Bird-dropping spider"],
        correctAnswer: 0,
        funFact: "There's no such thing as a 'Glass spider' - though some spiders are transparent!",
      },
      {
        id: "a64",
        question: "All but one of the following are true types of bears. Which is the odd one?",
        options: ["Moon bear", "Brown bear", "Black bear", "Sun bear"],
        correctAnswer: 0,
        funFact: "While there's an Asian black bear sometimes called 'moon bear,' it's not an official name!",
      },
      {
        id: "a65",
        question: "Which of these is not an actual breed of sheep?",
        options: ["Scottish black-face", "Dakota", "Hampshire", "Merino"],
        correctAnswer: 1,
        funFact: "Dakota is a U.S. state, not a sheep breed!",
      },
      {
        id: "a66",
        question: "One of these is not a true breed of chicken. Which one?",
        options: ["Hamburg", "Plymouth Rock", "Leghorn", "Red-tailed"],
        correctAnswer: 3,
        funFact: "Red-tailed describes hawks, not chickens!",
      },
      {
        id: "a67",
        question: "Which of the following is not a breed of pig?",
        options: ["Norwegian Yorkshire", "Vietnamese pot-belly", "Ridgeback", "Tokyo-X"],
        correctAnswer: 2,
        funFact: "Ridgeback is a dog breed, not a pig breed!",
      },
      {
        id: "a68",
        question: "What is a group of lions called?",
        options: ["Family", "Group", "School", "Pride"],
        correctAnswer: 3,
        funFact: "A group of lions is called a pride - usually consisting of related females and their cubs!",
      },
      {
        id: "a69",
        question: "There are more males then females in a pride.",
        options: ["False", "True"],
        correctAnswer: 0,
        funFact: "Lion prides are dominated by females - usually only 1-3 males in a pride of 10-15 lions!",
      },
      {
        id: "a70",
        question: "Generally, how many times in an interval of 5 hours do lions mate?",
        options: ["1", "5", "20", "10"],
        correctAnswer: 3,
        funFact: "Lions mate very frequently during breeding season - up to 40 times per day!",
      },
      {
        id: "a71",
        question: "What is the breed of animal created from the crossing of a male lion and a female tiger?",
        options: ["Tigon", "Tiges", "Ligon", "Liger"],
        correctAnswer: 3,
        funFact: "Ligers are the largest cats in the world and can weigh over 900 pounds!",
      },
      {
        id: "a72",
        question: "What is the breed of animal created from the crossing of a female lion and a male tiger?",
        options: ["Tigen", "Liger", "Tigon", "Liges"],
        correctAnswer: 2,
        funFact: "Tigons are smaller than ligers and are much rarer in captivity!",
      },
      {
        id: "a73",
        question: "What do male lions have which females do not possess?",
        options: ["An extra tooth", "A mane", "Longer nails", "Distinguished eyes"],
        correctAnswer: 1,
        funFact: "The male lion's mane serves to intimidate rivals and attract females!",
      },
      {
        id: "a74",
        question: "What is the average lifespan of a lion living in the wild?",
        options: ["20 - 30 years", "Less than 10 years", "10 -15 years", "Greater than 30 years"],
        correctAnswer: 2,
        funFact: "Wild lions typically live 10-15 years, while captive lions can live up to 20 years!",
      },
      {
        id: "a75",
        question: "Are male lions are generally stronger then female lions?",
        options: ["No", "Yes"],
        correctAnswer: 1,
        funFact: "Male lions are about 50% larger and stronger than females!",
      },
      {
        id: "a76",
        question: "Female lions hunt in a group.",
        options: ["False", "True"],
        correctAnswer: 1,
        funFact: "Female lions work together in coordinated hunts, while males usually don't participate!",
      },
      {
        id: "a77",
        question:
          "Cats twitch the tips of their tails slightly when hunting or when angry, while stronger twitching indicates what?",
        options: ["Stress", "Displeasure", "Boredom", "Playfulness"],
        correctAnswer: 1,
        funFact: "Strong tail twitching in cats usually indicates frustration or displeasure!",
      },
      {
        id: "a78",
        question: "If a cat pushes its face against your head, this means what?",
        options: ["Impatience", "Submission", "Acceptance", "Aggression"],
        correctAnswer: 2,
        funFact: "Head bunting is a sign of affection and acceptance - cats have scent glands on their heads!",
      },
      {
        id: "a79",
        question:
          "Cats generally purr when they are happy, but they can also be heard purring in what other situation?",
        options: [
          "When they are distressed or in pain",
          "When they are hunting or playing",
          "When they are hungry or thirsty",
          "When they are lonely or angry",
        ],
        correctAnswer: 0,
        funFact: "Cats also purr when stressed, injured, or giving birth - it may help them heal!",
      },
      {
        id: "a80",
        question: "How many different vocalization sounds does a cat make?",
        options: ["100", "200", "50", "150"],
        correctAnswer: 0,
        funFact: "Cats can make over 100 different vocal sounds, compared to dogs' 10!",
      },
      {
        id: "a81",
        question: "All cats are born with green eyes.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "Most kittens are born with blue eyes that change color as they mature!",
      },
      {
        id: "a82",
        question: "A cat's front paws have 5 toes and their back paws have 4.",
        options: ["False", "True"],
        correctAnswer: 1,
        funFact: "This is why cats' front paw prints look different from their back paw prints!",
      },
      {
        id: "a83",
        question: "What was the largest eagle ever found on Earth?",
        options: ["Golden Eagle", "Haast's Eagle", "Harpy Eagle", "Bald Eagle"],
        correctAnswer: 1,
        funFact: "Haast's Eagle from New Zealand had a 10-foot wingspan and hunted giant moa birds!",
      },
      {
        id: "a84",
        question: "Which term refers to the group formed by frogs and amphibians?",
        options: ["Drosophillia", "Herps", "Mollusks", "Nematodes"],
        correctAnswer: 1,
        funFact: "Herps (from herpetology) refers to reptiles and amphibians together!",
      },
      {
        id: "a85",
        question: "Which statement about elephants is untrue?",
        options: [
          "Elephants sleep standing up",
          "Elephants cry",
          "There are some pink elephants in India",
          "Elephants do not have great memories",
        ],
        correctAnswer: 3,
        funFact: "Elephants have excellent memories and can remember other elephants for decades!",
      },
      {
        id: "a86",
        question: "All pigs are classified as un-Kosher meaning they can not be eaten by Jewish people.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "While most pigs are not kosher, there are some exceptions in certain interpretations!",
      },
      {
        id: "a87",
        question: "What is alektorophobia?",
        options: [
          "The unreasonable fear of birds of prey",
          "The unreasonable fear of roaches",
          "The unreasonable fear of chickens",
          "The unreasonable fear of sharks",
        ],
        correctAnswer: 2,
        funFact: "Alektorophobia is the specific fear of chickens - it can be quite debilitating!",
      },
      {
        id: "a88",
        question: "How do scientists calculate the age of a fish?",
        options: [
          "They count all the teeth in the fish's mouth",
          "They measure the size of the fish and compare that to the average size of that type of fish",
          "They count the growth rings on the ear bone",
          "They count the teeth in the fish's lower lip",
        ],
        correctAnswer: 2,
        funFact: "Fish ear bones (otoliths) grow rings like tree rings, showing their age!",
      },
      {
        id: "a89",
        question:
          "Pound for pound, humans are not the strongest animals. What is considered the strongest species, pound for pound?",
        options: ["The Hercules beetle", "The leaf-cutting ant", "The red ant", "The atlas roach"],
        correctAnswer: 0,
        funFact: "Hercules beetles can lift 850 times their own body weight!",
      },
      {
        id: "a90",
        question: "Human beings have 23 pairs of chromosomes. Which animal has the most chromosomes?",
        options: ["minke whale", "millipedes", "elephants", "hermit crabs"],
        correctAnswer: 3,
        funFact: "Some hermit crab species have over 250 chromosomes!",
      },
      {
        id: "a91",
        question: "What type of animal is a lamprey?",
        options: ["worm", "fish", "insect", "amphibian"],
        correctAnswer: 1,
        funFact: "Lampreys are primitive fish that attach to other fish and feed on their blood!",
      },
      {
        id: "a92",
        question: "What is the name of the first book by Darwin that directly dealt with evolution?",
        options: [
          "Essay on the Principles of Population",
          "Totem and Taboo",
          "On the Origins of the Species",
          "The Descent of Man and the Selection in Relation to Sex",
        ],
        correctAnswer: 2,
        funFact: "Darwin's 'On the Origin of Species' revolutionized our understanding of life on Earth!",
      },
      {
        id: "a93",
        question: "Which of these animals has the largest paws?",
        options: ["An average mountain lion", "An average nematode", "An average lynx", "An average lichen"],
        correctAnswer: 2,
        funFact: "Lynx have huge paws that act like snowshoes for walking on snow!",
      },
      {
        id: "a94",
        question: "Sharks can only be found in salt water.",
        options: ["False", "True"],
        correctAnswer: 0,
        funFact: "Some sharks, like bull sharks, can live in both salt and fresh water!",
      },
      {
        id: "a95",
        question: "The smallest species of shark in the world is the Dwarf Lanternfish.",
        options: ["False", "True"],
        correctAnswer: 1,
        funFact: "The Dwarf Lanternfish shark is only about 8 inches long when fully grown!",
      },
      {
        id: "a96",
        question: "Sharks must eat continually in order to survive.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "Sharks can go weeks or even months without eating!",
      },
      {
        id: "a97",
        question: "Sharks can have up to nine gills on each side of their body.",
        options: ["False", "True"],
        correctAnswer: 0,
        funFact: "Most sharks have 5-7 gill slits, but never as many as nine!",
      },
      {
        id: "a98",
        question: "Rays and Skates are types of sharks.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Rays and skates are closely related to sharks - they're all cartilaginous fish!",
      },
      {
        id: "a99",
        question: "Sharks have poor vision.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "Many sharks actually have excellent vision, especially in low light!",
      },
      {
        id: "a100",
        question: "More shark attacks occur during the day than at night.",
        options: ["False", "True"],
        correctAnswer: 1,
        funFact: "Most shark attacks happen during daylight hours when more people are in the water!",
      },
      {
        id: "a101",
        question: "If attacked by a shark it is recommended that you punch the shark in the nose.",
        options: ["False", "True"],
        correctAnswer: 0,
        funFact: "You should actually aim for the eyes and gills - the nose isn't as sensitive as people think!",
      },
      {
        id: "a102",
        question: "Sharks are immune to cancer.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "This is a myth - sharks can and do get cancer, just like other animals!",
      },
      {
        id: "a103",
        question: "The dogfish is actually a common species of small shark.",
        options: ["False", "True"],
        correctAnswer: 1,
        funFact: "Dogfish are indeed small sharks, despite their misleading name!",
      },
      {
        id: "a104",
        question:
          "Despite the myth that Chihuahuas were descendants of the royal dog of the Aztecs, it is also believed that Spanish trade merchants brought Chihuahuas to which of these countries?",
        options: ["Venezuela", "United States", "Brazil", "Mexico"],
        correctAnswer: 3,
        funFact: "Chihuahuas are named after the Mexican state of Chihuahua!",
      },
      {
        id: "a105",
        question: "What maximum height at the withers can Chihuahuas reach?",
        options: ["24 inches (60 cm)", "15 inches (38 cm)", "12 inches (30 cm)", "9 inches (22 cm)"],
        correctAnswer: 1,
        funFact: "Most Chihuahuas are much smaller, typically 6-9 inches tall!",
      },
      {
        id: "a106",
        question: "Chihuahuas come in three colors: brindle, black, and camel.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "Chihuahuas actually come in many colors and patterns!",
      },
      {
        id: "a107",
        question: "Chihuahuas are the only dogs to be born with what?",
        options: ["An extra leg tendon", "Hairless inner ears", "An incomplete skull", "Two extra canine teeth"],
        correctAnswer: 2,
        funFact: "Chihuahuas are born with a soft spot on their skull called a molera!",
      },
      {
        id: "a108",
        question: "What is the average lifespan of Chihuahuas?",
        options: ["8 - 12 years", "8- 18 years", "8 - 26 years", "8 - 15 years"],
        correctAnswer: 1,
        funFact: "Chihuahuas are one of the longest-living dog breeds!",
      },
      {
        id: "a109",
        question: "The Chihuahua Gidget is famous for what reason?",
        options: [
          "Paris Hilton has it as a pet",
          "It was a fill-in mascot for the Georgia Bulldogs",
          "It was a mascot for Taco Bell",
          "It was a mascot for Taco John",
        ],
        correctAnswer: 2,
        funFact: "Gidget the Chihuahua starred in Taco Bell commercials in the late 1990s!",
      },
      {
        id: "a110",
        question: "The Chihuahua is the smallest dog breed in the world.",
        options: ["False", "True"],
        correctAnswer: 1,
        funFact: "Chihuahuas typically weigh between 2-6 pounds when fully grown!",
      },
      {
        id: "a111",
        question: "Chihuahuas are prone to hypoglycemia (low blood sugar).",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Small dogs like Chihuahuas need to eat frequently to maintain blood sugar levels!",
      },
      {
        id: "a112",
        question: "What does the word 'hippopotamus' mean?",
        options: ["Water pig", "Fat horse", "River horse", "River pig"],
        correctAnswer: 2,
        funFact: "Hippopotamus comes from Greek words meaning 'river horse'!",
      },
      {
        id: "a113",
        question: "For their size hippos are pretty fast runners and are much faster than humans.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Hippos can run up to 30 mph on land - much faster than humans!",
      },
      {
        id: "a114",
        question: "How long in years is the life span of an average wild hippopotamus?",
        options: ["10-20", "40-50", "30-40", "20-30"],
        correctAnswer: 1,
        funFact: "Hippos can live 40-50 years in the wild, making them quite long-lived!",
      },
      {
        id: "a115",
        question: "Hippos secrete a red substance known as blood sweat that protects them from the sun.",
        options: ["False", "True"],
        correctAnswer: 1,
        funFact: "This red secretion acts as both sunscreen and antibiotic for hippos!",
      },
      {
        id: "a116",
        question: "Hippos are related to cetaceans (whales and porpoises).",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Hippos are the closest living land relatives to whales and dolphins!",
      },
      {
        id: "a117",
        question: "The Spectacled bear makes its habitat around the Andes tropical basin.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Spectacled bears are the only bears native to South America!",
      },
      {
        id: "a118",
        question: "This is the basic food of the sea. Billions upon billions of these organisms live in the sea.",
        options: ["Seaweed", "Plankton", "Crabs", "Shrimp"],
        correctAnswer: 1,
        funFact: "Plankton forms the base of almost all marine food chains!",
      },
      {
        id: "a119",
        question: "This is the result of the gravitational pull from the moon and sun.",
        options: ["Migration of certain species of whales", "Tides", "Shoreline", "Waves"],
        correctAnswer: 1,
        funFact: "Tides are caused by the gravitational forces of the moon and sun on Earth's oceans!",
      },
      {
        id: "a120",
        question:
          "These creatures look like flowers as they grow attached to rocks. Their tentacles open like fleshy petals and contract whenever danger is near.",
        options: ["Kelp", "Jellyfish", "Sponges", "Sea Anemones"],
        correctAnswer: 3,
        funFact: "Sea anemones are actually animals, not plants, despite looking like flowers!",
      },
      {
        id: "a121",
        question:
          "This sea animal, widely considered the most valuable shellfish, is common in shallow, warmer waters of all oceans.",
        options: ["Oyster", "Shrimp", "Scallop", "Lobster"],
        correctAnswer: 0,
        funFact: "Oysters can produce pearls and are considered a delicacy worldwide!",
      },
      {
        id: "a122",
        question: "This crab is not really a crab, but an arthropod. Its closest relative is the spider.",
        options: ["Fiddler Crab", "Horseshoe crab", "Spider Crab", "Rock Crab"],
        correctAnswer: 1,
        funFact: "Horseshoe crabs are living fossils that have remained unchanged for 450 million years!",
      },
      {
        id: "a123",
        question:
          "These worms are not in fact worms, but bivalves. They enter wood as larvae, where they remain and grow, burrowing through the wood.",
        options: ["Sea Mice", "Ribbon Worms", "Lugworms", "Shipworms"],
        correctAnswer: 3,
        funFact: "Shipworms were the bane of wooden ships and can completely destroy wooden structures!",
      },
      {
        id: "a124",
        question: "Squid and octopus are mollusks.",
        options: ["False", "True"],
        correctAnswer: 1,
        funFact: "Squid and octopus are cephalopod mollusks - the most intelligent invertebrates!",
      },
      {
        id: "a125",
        question: "The Pacific lobster has large pincers and a spiny shell.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "Pacific lobsters (spiny lobsters) don't have large claws like their Atlantic cousins!",
      },
      {
        id: "a126",
        question: "Also called Sea Biscuit, this animal lives in deeper water half-buried in the sand.",
        options: ["Sand Dollar", "Star Fish", "Scallop", "Mussel"],
        correctAnswer: 0,
        funFact: "Sand dollars are actually flattened sea urchins that burrow in sandy ocean floors!",
      },
      {
        id: "a127",
        question:
          "The red kangaroo appears on the Coat of Arms of Australia together with what other endemic Australian animal?",
        options: ["Emu", "Platypus", "Dingo", "Koala"],
        correctAnswer: 0,
        funFact: "The kangaroo and emu were chosen because they can't walk backwards, symbolizing progress!",
      },
      {
        id: "a128",
        question: "Which of these mammals was brought to Australia by humans?",
        options: ["The echidna", "The dingo", "The koala", "The Tasmanian tiger"],
        correctAnswer: 1,
        funFact: "Dingoes were brought to Australia by humans about 4,000 years ago!",
      },
      {
        id: "a129",
        question: "Which of the following statements about echidnas, mammals native to Australia, is wrong?",
        options: [
          "Echidnas are covered with spines",
          "Echidnas have snouts",
          "Echidnas lay eggs",
          "Echidnas are marsupials",
        ],
        correctAnswer: 3,
        funFact: "Echidnas are monotremes (egg-laying mammals), not marsupials!",
      },
      {
        id: "a130",
        question: "The diet of the koala consists mainly of what plant species?",
        options: ["Eucalyptus", "Bamboo", "Willow", "Cork Oak"],
        correctAnswer: 0,
        funFact: "Koalas eat almost exclusively eucalyptus leaves and are very picky about which species!",
      },
      {
        id: "a131",
        question: "Which one of these Australian reptiles is the largest living crocodile in the world?",
        options: ["The thorny devil", "The weedy sea dragon", "The blue-tongued skink", "The saltwater crocodile"],
        correctAnswer: 3,
        funFact: "Saltwater crocodiles can grow over 20 feet long and weigh more than a ton!",
      },
      {
        id: "a132",
        question: "This Australian monotreme lays eggs and has a remarkable sense of electroception.",
        options: ["Platypus", "Red kangaroo", "Dingo", "Emu"],
        correctAnswer: 0,
        funFact: "Platypuses can detect electrical fields generated by muscle contractions of other animals!",
      },
      {
        id: "a133",
        question: "Which Australian animal is the largest living carnivorous marsupial on Earth?",
        options: ["The Tasmanian tiger", "The Tasmanian devil", "The platypus", "The red kangaroo"],
        correctAnswer: 1,
        funFact: "Tasmanian devils have the strongest bite force of any living marsupial!",
      },
      {
        id: "a134",
        question: "Qantas, Australia's largest airline company, has what Australian animal on its red-and-white logo?",
        options: ["Koala", "Kangaroo", "Emu", "Tasmanian devil"],
        correctAnswer: 1,
        funFact: "The kangaroo symbolizes Qantas's forward movement and Australian identity!",
      },
      {
        id: "a135",
        question: "What is the difference between the male and the female Galah, a cockatoo bird native to Australia?",
        options: [
          "There is no difference between them",
          "Males and females have different eye colour",
          "Galah males are crested",
          "Galah females have shorter tails",
        ],
        correctAnswer: 1,
        funFact: "Male Galahs have dark brown/black eyes while females have red/pink eyes!",
      },
      {
        id: "a136",
        question: "What is the average weight of the Tasmanian Pygmy Possum?",
        options: ["About 250g", "About 50g", "About 100g", "About 7g"],
        correctAnswer: 3,
        funFact: "The Tasmanian Pygmy Possum is one of the world's smallest marsupials!",
      },
      {
        id: "a137",
        question:
          "Which lizard can squirt blood from the corners of its eyes in order to confuse and drive back its enemies?",
        options: ["Anole", "Gila monster", "Horned lizard", "Komodo dragon"],
        correctAnswer: 2,
        funFact: "Horned lizards can shoot blood up to 5 feet from their eyes as a defense mechanism!",
      },
      {
        id: "a138",
        question: "The venomous lizard Gila monster was named after what?",
        options: ["The Gila River basin", "The Gila Expedition 1857", "Alberto Gilardino", "Gilligan's Island"],
        correctAnswer: 0,
        funFact: "The Gila monster is named after the Gila River basin in Arizona and New Mexico!",
      },
      {
        id: "a139",
        question: "The Komodo dragon, the largest living lizard on Earth, lives in which part of the world?",
        options: ["North America", "Indonesia", "South-western China", "Madagascar"],
        correctAnswer: 1,
        funFact: "Komodo dragons are found only on a few Indonesian islands including Komodo Island!",
      },
      {
        id: "a140",
        question:
          "Which term refers to the self-defense mechanism which allows lizards to break off their tails when captured?",
        options: ["Apotemnophilia", "Autonomy", "Autotomy", "Autism"],
        correctAnswer: 2,
        funFact: "Autotomy allows lizards to escape predators, and many can regrow their tails!",
      },
      {
        id: "a141",
        question: "Which of these statements about geckos is true?",
        options: [
          "Geckos have toe pads which help them climb smooth vertical surfaces",
          "All of these",
          "Geckos can make chirping sounds",
          "Geckos feed on insects",
        ],
        correctAnswer: 1,
        funFact: "Geckos are amazing climbers and many species are quite vocal!",
      },
      {
        id: "a142",
        question: "Chameleons are lizards that can change their colour. What does Chameleon mean in Greek?",
        options: ["Green melon", "Karma lion", "Colourful", "Earth lion"],
        correctAnswer: 3,
        funFact: "Chameleon comes from Greek words meaning 'earth lion'!",
      },
      {
        id: "a143",
        question: "Geckos have immovable eyelids and can't blink. How do they keep their eyes clean?",
        options: [
          "A tiny insect lives under their eyelids and cleans their eyes",
          "They lick their own eyes",
          "They dip their eyes in water",
          "They cover their eyes with their toes",
        ],
        correctAnswer: 1,
        funFact: "Geckos use their long tongues to lick their eyes clean - it's quite a sight!",
      },
      {
        id: "a144",
        question: "The lizards which do not have legs are commonly known by what name?",
        options: ["Glass lizards", "Monitor lizards", "Skinks", "Iguanas"],
        correctAnswer: 0,
        funFact: "Glass lizards look like snakes but are actually legless lizards with eyelids!",
      },
      {
        id: "a145",
        question: "Which of these lizard species is not endangered?",
        options: ["Eastern Bearded Dragon", "Blunt-nosed Leopard Lizard", "Mona Ground Iguana", "Komodo Dragon"],
        correctAnswer: 0,
        funFact: "Eastern Bearded Dragons are actually quite common and popular as pets!",
      },
      {
        id: "a146",
        question: "No lizard species live on which continent?",
        options: ["South America", "Antarctica", "Europe", "Asia"],
        correctAnswer: 1,
        funFact: "Antarctica is too cold for any reptiles, including lizards!",
      },
      {
        id: "a147",
        question:
          "This shark is considered a filter-feeder. Its diet consists mainly of plankton, krill, and macro-algae.",
        options: ["whale shark", "bull shark", "great white shark", "pygmy shark"],
        correctAnswer: 0,
        funFact: "Whale sharks are the largest fish in the world but eat some of the smallest organisms!",
      },
      {
        id: "a148",
        question: "This shark's white belly and grey back make it difficult for prey to spot.",
        options: ["hammerhead shark", "tiger shark", "great white shark", "whale shark"],
        correctAnswer: 2,
        funFact: "This coloration is called countershading - it's perfect camouflage in the ocean!",
      },
      {
        id: "a149",
        question: "Sharks have no bones.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Shark skeletons are made entirely of cartilage, which is lighter and more flexible than bone!",
      },
      {
        id: "a150",
        question: "Have sharks been around for about 400 million years?",
        options: ["No", "Yes"],
        correctAnswer: 1,
        funFact: "Sharks have survived multiple mass extinctions and are older than trees!",
      },
      {
        id: "a151",
        question: "How tall can a giraffe grow?",
        options: ["12 feet", "18 feet", "24 feet", "30 feet"],
        correctAnswer: 1,
        funFact: "Giraffes can grow up to 18 feet tall - that's about 3 stories high!",
      },
      {
        id: "a152",
        question: "A giraffe's tongue can be up to how many inches long?",
        options: ["12 inches", "18 inches", "21 inches", "24 inches"],
        correctAnswer: 2,
        funFact: "A giraffe's 21-inch tongue is dark colored to protect it from sunburn!",
      },
      {
        id: "a153",
        question: "How many hours a day do giraffes sleep?",
        options: ["2 hours", "6 hours", "8 hours", "12 hours"],
        correctAnswer: 0,
        funFact: "Giraffes only need about 2 hours of sleep per day - they're the ultimate insomniacs!",
      },
      {
        id: "a154",
        question: "A giraffe's heart weighs about how much?",
        options: ["5 pounds", "15 pounds", "25 pounds", "35 pounds"],
        correctAnswer: 2,
        funFact: "A giraffe's heart weighs 25 pounds and pumps blood 6 feet up to its brain!",
      },
      {
        id: "a155",
        question: "Baby giraffes drop how far to the ground when they are born?",
        options: ["2 feet", "4 feet", "6 feet", "8 feet"],
        correctAnswer: 2,
        funFact: "Baby giraffes get quite a welcome to the world with a 6-foot drop!",
      },
      {
        id: "a156",
        question: "Giraffes have the same number of neck vertebrae as humans.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Both giraffes and humans have 7 neck vertebrae - giraffes' are just much longer!",
      },
      {
        id: "a157",
        question: "What is the most popular breed of dog in America?",
        options: ["German Shepherd", "Golden Retriever", "Labrador Retriever", "Beagle"],
        correctAnswer: 2,
        funFact: "Labrador Retrievers have been America's most popular dog breed for over 30 years!",
      },
      {
        id: "a158",
        question: "Beagles were originally bred for what purpose?",
        options: ["Companionship", "Hunting hare", "Guarding", "Herding sheep"],
        correctAnswer: 1,
        funFact: "Beagles were specifically bred to hunt hare and have incredible scenting abilities!",
      },
      {
        id: "a159",
        question: "What is the average lifespan of a Beagle?",
        options: ["8-10 years", "10-12 years", "12-15 years", "15-18 years"],
        correctAnswer: 2,
        funFact: "Beagles are generally healthy dogs with a good lifespan of 12-15 years!",
      },
      {
        id: "a160",
        question: "Beagles are known for their distinctive howl called what?",
        options: ["Baying", "Barking", "Yipping", "Howling"],
        correctAnswer: 0,
        funFact: "Beagle baying is their way of communicating during hunts - it's quite musical!",
      },
      {
        id: "a161",
        question: "What is the most common pet fish?",
        options: ["Betta", "Guppy", "Goldfish", "Angelfish"],
        correctAnswer: 2,
        funFact: "Goldfish have been kept as pets for over 1,000 years!",
      },
      {
        id: "a162",
        question: "How long can goldfish live?",
        options: ["2-3 years", "5-10 years", "10-30 years", "50+ years"],
        correctAnswer: 2,
        funFact: "With proper care, goldfish can live 10-30 years - much longer than most people think!",
      },
      {
        id: "a163",
        question: "Goldfish have a memory span of only 3 seconds.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "This is a myth! Goldfish can remember things for months, not seconds!",
      },
      {
        id: "a164",
        question: "What do you call a group of goldfish?",
        options: ["School", "Flock", "Troubling", "All of the above"],
        correctAnswer: 3,
        funFact: "Goldfish groups can be called a school, flock, or troubling - quite versatile!",
      },
      {
        id: "a165",
        question: "Which bird of prey has the best eyesight?",
        options: ["Eagle", "Hawk", "Falcon", "Owl"],
        correctAnswer: 0,
        funFact: "Eagles can see 4-8 times better than humans and spot prey from miles away!",
      },
      {
        id: "a166",
        question: "Which bird can fly backwards?",
        options: ["Hummingbird", "Woodpecker", "Robin", "Sparrow"],
        correctAnswer: 0,
        funFact: "Hummingbirds are the only birds that can fly backwards, upside down, and hover!",
      },
      {
        id: "a167",
        question: "What is the fastest bird in the world?",
        options: ["Golden Eagle", "Peregrine Falcon", "Gyrfalcon", "Sparrowhawk"],
        correctAnswer: 1,
        funFact: "Peregrine Falcons can dive at speeds over 240 mph when hunting!",
      },
      {
        id: "a168",
        question: "Which bird has the largest wingspan?",
        options: ["Bald Eagle", "Condor", "Albatross", "Pelican"],
        correctAnswer: 2,
        funFact: "Wandering Albatrosses have wingspans up to 12 feet - perfect for ocean gliding!",
      },
      {
        id: "a169",
        question: "What is the largest bear in North America?",
        options: ["Black Bear", "Brown Bear", "Polar Bear", "Grizzly Bear"],
        correctAnswer: 2,
        funFact: "Polar bears are the largest bears and can weigh up to 1,500 pounds!",
      },
      {
        id: "a170",
        question: "Which North American animal is known for playing dead?",
        options: ["Raccoon", "Skunk", "Opossum", "Porcupine"],
        correctAnswer: 2,
        funFact: "Opossums 'play possum' by going limp and appearing dead when threatened!",
      },
      {
        id: "a171",
        question: "What is the state animal of California?",
        options: ["Golden Bear", "Mountain Lion", "Condor", "Sea Otter"],
        correctAnswer: 0,
        funFact: "The California Grizzly Bear is the state animal, though they're now extinct in California!",
      },
      {
        id: "a172",
        question: "Which animal is known as the 'ship of the desert'?",
        options: ["Horse", "Donkey", "Camel", "Llama"],
        correctAnswer: 2,
        funFact: "Camels can travel long distances without water, making them perfect desert transportation!",
      },
      {
        id: "a173",
        question: "How far can a skunk spray its scent?",
        options: ["3 feet", "6 feet", "10 feet", "15 feet"],
        correctAnswer: 2,
        funFact: "Skunks can accurately spray their terrible scent up to 10 feet away!",
      },
      {
        id: "a174",
        question: "What do skunks primarily eat?",
        options: ["Plants only", "Meat only", "Insects and small animals", "Garbage"],
        correctAnswer: 2,
        funFact: "Skunks are omnivores but prefer insects, grubs, and small rodents!",
      },
      {
        id: "a175",
        question: "Baby skunks are called what?",
        options: ["Pups", "Kits", "Cubs", "Sprays"],
        correctAnswer: 1,
        funFact: "Baby skunks are called kits and are born unable to spray for several weeks!",
      },
      {
        id: "a176",
        question: "How many species of foxes are there?",
        options: ["12", "23", "37", "45"],
        correctAnswer: 2,
        funFact: "There are 37 species of foxes worldwide, from tiny fennec foxes to large red foxes!",
      },
      {
        id: "a177",
        question: "What sound do foxes make?",
        options: ["Bark", "Howl", "Scream", "All of the above"],
        correctAnswer: 3,
        funFact: "Foxes make over 40 different sounds including barks, screams, and chattering!",
      },
      {
        id: "a178",
        question: "Arctic foxes change color with the seasons.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Arctic foxes are white in winter and brown/blue in summer for perfect camouflage!",
      },
      {
        id: "a179",
        question: "What is a group of foxes called?",
        options: ["Pack", "Skulk", "Pride", "Flock"],
        correctAnswer: 1,
        funFact: "A group of foxes is called a skulk - quite fitting for these sneaky animals!",
      },
      {
        id: "a180",
        question: "How many eggs can a chicken lay per year?",
        options: ["100", "200", "300", "400"],
        correctAnswer: 2,
        funFact: "A good laying hen can produce about 300 eggs per year!",
      },
      {
        id: "a181",
        question: "What is a male chicken called?",
        options: ["Buck", "Rooster", "Tom", "Bull"],
        correctAnswer: 1,
        funFact: "Male chickens are roosters, females are hens, and babies are chicks!",
      },
      {
        id: "a182",
        question: "Chickens can fly.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Chickens can fly short distances, usually to escape predators or reach roosts!",
      },
      {
        id: "a183",
        question: "How many breeds of chickens are there?",
        options: ["25", "50", "100", "Over 500"],
        correctAnswer: 3,
        funFact: "There are over 500 chicken breeds worldwide, from tiny bantams to giant Jerseys!",
      },
      {
        id: "a184",
        question: "What is the roar of a lion called?",
        options: ["Howl", "Bellow", "Roar", "Call"],
        correctAnswer: 2,
        funFact: "A lion's roar can be heard up to 5 miles away and is used to mark territory!",
      },
      {
        id: "a185",
        question: "How fast can a lion run?",
        options: ["30 mph", "40 mph", "50 mph", "60 mph"],
        correctAnswer: 2,
        funFact: "Lions can reach speeds of 50 mph in short bursts when hunting!",
      },
      {
        id: "a186",
        question: "Lions are the only cats that live in groups.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Lions are unique among cats for their social structure and group living!",
      },
      {
        id: "a187",
        question: "How many hours a day do lions sleep?",
        options: ["8 hours", "12 hours", "16 hours", "20 hours"],
        correctAnswer: 3,
        funFact: "Lions sleep up to 20 hours a day - they're the ultimate lazy cats!",
      },
      {
        id: "a188",
        question: "What type of penguin is the largest?",
        options: ["King Penguin", "Emperor Penguin", "Adelie Penguin", "Chinstrap Penguin"],
        correctAnswer: 1,
        funFact: "Emperor Penguins can stand 4 feet tall and weigh up to 90 pounds!",
      },
      {
        id: "a189",
        question: "How deep can penguins dive?",
        options: ["100 feet", "500 feet", "1,000 feet", "1,800 feet"],
        correctAnswer: 3,
        funFact: "Emperor Penguins can dive over 1,800 feet deep and hold their breath for 20 minutes!",
      },
      {
        id: "a190",
        question: "Penguins can only be found in Antarctica.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "Penguins live throughout the Southern Hemisphere, including Africa and South America!",
      },
      {
        id: "a191",
        question: "How do penguins keep their eggs warm?",
        options: ["Build nests", "Bury them", "Balance on feet", "Use body heat"],
        correctAnswer: 2,
        funFact: "Emperor Penguin fathers balance eggs on their feet under a warm flap of skin!",
      },
      {
        id: "a192",
        question: "What color is a polar bear's skin?",
        options: ["White", "Pink", "Black", "Brown"],
        correctAnswer: 2,
        funFact: "Polar bears have black skin under their white fur to absorb heat from the sun!",
      },
      {
        id: "a193",
        question: "How much can a polar bear weigh?",
        options: ["500 pounds", "800 pounds", "1,200 pounds", "1,500 pounds"],
        correctAnswer: 3,
        funFact: "Large male polar bears can weigh up to 1,500 pounds - that's like a small car!",
      },
      {
        id: "a194",
        question: "Polar bears are excellent swimmers.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Polar bears can swim for hours and have been spotted 60 miles from shore!",
      },
      {
        id: "a195",
        question: "What do polar bears primarily eat?",
        options: ["Fish", "Seals", "Penguins", "Berries"],
        correctAnswer: 1,
        funFact: "Polar bears primarily hunt seals, waiting by breathing holes in the ice!",
      },
      {
        id: "a196",
        question: "What does the name 'Tyrannosaurus Rex' mean?",
        options: ["Giant Lizard", "Terrible Lizard", "King Lizard", "Tyrant Lizard King"],
        correctAnswer: 3,
        funFact: "T-Rex means 'Tyrant Lizard King' - quite fitting for this massive predator!",
      },
      {
        id: "a197",
        question: "How long were T-Rex arms?",
        options: ["1 foot", "3 feet", "5 feet", "7 feet"],
        correctAnswer: 1,
        funFact: "Despite being tiny compared to its body, T-Rex arms were incredibly strong!",
      },
      {
        id: "a198",
        question: "Dinosaurs lived at the same time as humans.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "Dinosaurs went extinct 65 million years before humans appeared!",
      },
      {
        id: "a199",
        question: "What is the largest dinosaur ever discovered?",
        options: ["T-Rex", "Brontosaurus", "Argentinosaurus", "Triceratops"],
        correctAnswer: 2,
        funFact: "Argentinosaurus could reach 115 feet long and weigh 80 tons!",
      },
      {
        id: "a200",
        question: "Birds are descendants of dinosaurs.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Birds are literally living dinosaurs - they evolved from theropod dinosaurs!",
      },
      {
        id: "a201",
        question: "What is the most popular breed of dog in the United States?",
        options: ["Golden Retriever", "German Shepherd", "Labrador Retriever", "Bulldog"],
        correctAnswer: 2,
        funFact: "Labrador Retrievers have held the #1 spot for over 30 consecutive years!",
      },
      {
        id: "a202",
        question: "Labradors were originally bred in which country?",
        options: ["Labrador, Canada", "England", "Newfoundland, Canada", "Scotland"],
        correctAnswer: 2,
        funFact: "Despite their name, Labradors actually originated in Newfoundland, not Labrador!",
      },
      {
        id: "a203",
        question: "What were Labrador Retrievers originally used for?",
        options: ["Hunting birds", "Retrieving fishing nets", "Guarding homes", "Herding sheep"],
        correctAnswer: 1,
        funFact: "Labs helped fishermen retrieve nets and fish that escaped from fishing lines!",
      },
      {
        id: "a204",
        question: "How many recognized colors do Labrador Retrievers come in?",
        options: ["2", "3", "4", "5"],
        correctAnswer: 1,
        funFact: "Labs come in three official colors: yellow, black, and chocolate!",
      },
      {
        id: "a205",
        question: "What is the largest living reptile?",
        options: ["Komodo Dragon", "Saltwater Crocodile", "Green Anaconda", "Reticulated Python"],
        correctAnswer: 1,
        funFact: "Saltwater crocodiles can grow over 23 feet long and weigh more than 2,000 pounds!",
      },
      {
        id: "a206",
        question: "How long can crocodiles hold their breath underwater?",
        options: ["15 minutes", "30 minutes", "1 hour", "2 hours"],
        correctAnswer: 2,
        funFact: "Crocodiles can hold their breath for up to an hour while hunting underwater!",
      },
      {
        id: "a207",
        question: "Crocodiles are more closely related to birds than to lizards.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Crocodiles and birds are both archosaurs and share a more recent common ancestor!",
      },
      {
        id: "a208",
        question: "How many teeth can a crocodile have in its lifetime?",
        options: ["1,000", "2,000", "3,000", "4,000"],
        correctAnswer: 3,
        funFact: "Crocodiles can go through 4,000 teeth in their lifetime, constantly replacing them!",
      },
      {
        id: "a209",
        question: "What do beavers use their tails for?",
        options: ["Swimming only", "Balance and communication", "Storing fat", "All of the above"],
        correctAnswer: 3,
        funFact: "Beaver tails are multi-purpose tools for swimming, balance, fat storage, and slapping warnings!",
      },
      {
        id: "a210",
        question: "How long can beaver dams be?",
        options: ["100 feet", "500 feet", "1,000 feet", "2,800 feet"],
        correctAnswer: 3,
        funFact: "The longest beaver dam ever found was 2,800 feet long in Alberta, Canada!",
      },
      {
        id: "a211",
        question: "Beavers' teeth never stop growing.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Beavers must constantly gnaw on wood to keep their ever-growing teeth from getting too long!",
      },
      {
        id: "a212",
        question: "What are baby beavers called?",
        options: ["Pups", "Kits", "Cubs", "Calves"],
        correctAnswer: 1,
        funFact: "Baby beavers are called kits and can swim within 24 hours of being born!",
      },
      {
        id: "a213",
        question: "How many species of butterflies are there worldwide?",
        options: ["5,000", "10,000", "17,500", "25,000"],
        correctAnswer: 2,
        funFact: "There are approximately 17,500 butterfly species worldwide with incredible diversity!",
      },
      {
        id: "a214",
        question: "What do butterflies taste with?",
        options: ["Their antennae", "Their proboscis", "Their feet", "Their wings"],
        correctAnswer: 2,
        funFact: "Butterflies taste with their feet to determine if a leaf is suitable for laying eggs!",
      },
      {
        id: "a215",
        question: "How long do most butterflies live?",
        options: ["1 week", "2-5 weeks", "6 months", "1 year"],
        correctAnswer: 1,
        funFact: "Most butterflies live only 2-5 weeks, though some species like Monarchs can live much longer!",
      },
      {
        id: "a216",
        question: "Butterflies can see ultraviolet light.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Butterflies can see UV patterns on flowers that are invisible to human eyes!",
      },
      {
        id: "a217",
        question: "How many muscles do cats have in each ear?",
        options: ["12", "24", "32", "40"],
        correctAnswer: 2,
        funFact: "Cats have 32 muscles in each ear, allowing them to rotate their ears 180 degrees!",
      },
      {
        id: "a218",
        question: "What is a group of cats called?",
        options: ["Pack", "Clowder", "Pride", "Colony"],
        correctAnswer: 1,
        funFact: "A group of cats is called a clowder, though they're usually solitary animals!",
      },
      {
        id: "a219",
        question: "Cats spend what percentage of their lives sleeping?",
        options: ["50%", "60%", "70%", "80%"],
        correctAnswer: 2,
        funFact: "Cats sleep 12-16 hours a day, spending about 70% of their lives asleep!",
      },
      {
        id: "a220",
        question: "How many hearts do earthworms have?",
        options: ["1", "3", "5", "10"],
        correctAnswer: 2,
        funFact: "Earthworms have 5 hearts (or aortic arches) that pump blood through their bodies!",
      },
      {
        id: "a221",
        question: "Earthworms are both male and female.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Earthworms are hermaphrodites, having both male and female reproductive organs!",
      },
      {
        id: "a222",
        question: "How much of their body weight can earthworms eat per day?",
        options: ["25%", "50%", "75%", "100%"],
        correctAnswer: 3,
        funFact: "Earthworms can eat their own body weight in organic matter every single day!",
      },
      {
        id: "a223",
        question: "How many brains does an octopus have?",
        options: ["1", "3", "8", "9"],
        correctAnswer: 3,
        funFact: "Octopuses have 9 brains - one central brain and one in each of their 8 arms!",
      },
      {
        id: "a224",
        question: "How many hearts does an octopus have?",
        options: ["1", "2", "3", "4"],
        correctAnswer: 2,
        funFact: "Octopuses have 3 hearts - two pump blood to the gills, one pumps to the body!",
      },
      {
        id: "a225",
        question: "What color is octopus blood?",
        options: ["Red", "Blue", "Green", "Purple"],
        correctAnswer: 1,
        funFact: "Octopus blood is blue because it contains copper-based hemocyanin instead of iron!",
      },
      {
        id: "a226",
        question: "Octopuses are colorblind.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Despite being colorblind, octopuses can perfectly match their surroundings using skin sensors!",
      },
      {
        id: "a227",
        question: "What is the largest subspecies of brown bear?",
        options: ["Grizzly Bear", "Kodiak Bear", "European Brown Bear", "Himalayan Brown Bear"],
        correctAnswer: 1,
        funFact: "Kodiak bears can weigh up to 1,500 pounds and stand 10 feet tall on hind legs!",
      },
      {
        id: "a228",
        question: "How fast can a grizzly bear run?",
        options: ["25 mph", "35 mph", "45 mph", "55 mph"],
        correctAnswer: 1,
        funFact: "Grizzly bears can run up to 35 mph - faster than any human!",
      },
      {
        id: "a229",
        question: "Grizzly bears are excellent swimmers.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Grizzlies are powerful swimmers and have been seen swimming miles between islands!",
      },
      {
        id: "a230",
        question: "How long do grizzly bears hibernate?",
        options: ["2-3 months", "4-5 months", "5-7 months", "8-9 months"],
        correctAnswer: 2,
        funFact: "Grizzly bears can hibernate for 5-7 months without eating, drinking, or eliminating waste!",
      },
      {
        id: "a231",
        question: "What is the most popular dog breed for families?",
        options: ["Golden Retriever", "Labrador Retriever", "German Shepherd", "Beagle"],
        correctAnswer: 0,
        funFact: "Golden Retrievers are known for their gentle, patient temperament with children!",
      },
      {
        id: "a232",
        question: "How many different dog breeds are recognized worldwide?",
        options: ["150", "250", "340", "500"],
        correctAnswer: 2,
        funFact: "There are approximately 340 recognized dog breeds worldwide with incredible diversity!",
      },
      {
        id: "a233",
        question: "What is the smallest dog breed?",
        options: ["Yorkshire Terrier", "Chihuahua", "Maltese", "Papillon"],
        correctAnswer: 1,
        funFact: "Chihuahuas typically weigh 2-6 pounds and can fit in a teacup when young!",
      },
      {
        id: "a234",
        question: "Dogs have a sense of time.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Dogs can tell time and often know when their owners are coming home!",
      },
      {
        id: "a235",
        question: "When did the dodo bird go extinct?",
        options: ["1681", "1715", "1750", "1800"],
        correctAnswer: 0,
        funFact: "The dodo went extinct around 1681, less than 100 years after humans discovered them!",
      },
      {
        id: "a236",
        question: "Where did dodo birds live?",
        options: ["Madagascar", "Mauritius", "Seychelles", "Galapagos"],
        correctAnswer: 1,
        funFact: "Dodos were found only on the island of Mauritius in the Indian Ocean!",
      },
      {
        id: "a237",
        question: "Why couldn't dodo birds fly?",
        options: ["Broken wings", "Too heavy", "No predators", "Lazy"],
        correctAnswer: 2,
        funFact: "With no natural predators, dodos evolved to be flightless and lost their fear of humans!",
      },
      {
        id: "a238",
        question: "How fast can a cheetah run?",
        options: ["50 mph", "60 mph", "70 mph", "80 mph"],
        correctAnswer: 2,
        funFact: "Cheetahs can reach 70 mph in just 3 seconds - faster than most sports cars!",
      },
      {
        id: "a239",
        question: "How long can a cheetah maintain top speed?",
        options: ["10 seconds", "30 seconds", "1 minute", "5 minutes"],
        correctAnswer: 1,
        funFact: "Cheetahs can only maintain top speed for about 30 seconds before overheating!",
      },
      {
        id: "a240",
        question: "Cheetahs cannot roar.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Cheetahs can't roar but they can purr, chirp, and make bird-like sounds!",
      },
      {
        id: "a241",
        question: "What makes cheetahs different from other big cats?",
        options: ["Semi-retractable claws", "Spotted coat", "Long legs", "All of the above"],
        correctAnswer: 3,
        funFact: "Cheetahs have many unique features that make them the ultimate sprinters!",
      },
      {
        id: "a242",
        question: "How high can frogs jump?",
        options: ["5 times their length", "10 times their length", "20 times their length", "50 times their length"],
        correctAnswer: 2,
        funFact: "Some frogs can jump 20 times their own body length in a single leap!",
      },
      {
        id: "a243",
        question: "Frogs drink water through their skin.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Frogs absorb water through their skin rather than drinking it through their mouths!",
      },
      {
        id: "a244",
        question: "What is a group of frogs called?",
        options: ["Army", "Colony", "Knot", "All of the above"],
        correctAnswer: 3,
        funFact: "Frogs can be called an army, colony, or knot depending on the situation!",
      },
      {
        id: "a245",
        question: "How many species of frogs are there?",
        options: ["2,000", "4,000", "7,000", "10,000"],
        correctAnswer: 2,
        funFact: "There are over 7,000 known frog species with new ones discovered regularly!",
      },
      {
        id: "a246",
        question: "Are zebras black with white stripes or white with black stripes?",
        options: ["Black with white stripes", "White with black stripes", "Both", "Neither"],
        correctAnswer: 0,
        funFact: "Zebras are black with white stripes - their skin underneath is black!",
      },
      {
        id: "a247",
        question: "Do all zebras have the same stripe pattern?",
        options: ["Yes", "No"],
        correctAnswer: 1,
        funFact: "Every zebra has a unique stripe pattern, like human fingerprints!",
      },
      {
        id: "a248",
        question: "Why do zebras have stripes?",
        options: ["Camouflage", "Confuse predators", "Regulate temperature", "All of the above"],
        correctAnswer: 3,
        funFact: "Zebra stripes serve multiple purposes including confusing flies and predators!",
      },
      {
        id: "a249",
        question: "How much can ants lift compared to their body weight?",
        options: ["10 times", "25 times", "50 times", "100 times"],
        correctAnswer: 2,
        funFact: "Ants can lift 50 times their own body weight - imagine if humans could do that!",
      },
      {
        id: "a250",
        question: "How many ants are there for every human on Earth?",
        options: ["1,000", "10,000", "1 million", "1.6 million"],
        correctAnswer: 3,
        funFact: "There are approximately 1.6 million ants for every human on the planet!",
      },
      {
        id: "a251",
        question: "Ants never sleep.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "Ants do sleep, but only for about 1 minute at a time, several times per day!",
      },
      {
        id: "a252",
        question: "How do ants communicate?",
        options: ["Chemical signals", "Touch", "Sound", "All of the above"],
        correctAnswer: 3,
        funFact: "Ants use pheromones, touch, and even sound to communicate with their colony!",
      },
      {
        id: "a253",
        question: "What color are flamingos when they're born?",
        options: ["Pink", "White", "Gray", "Red"],
        correctAnswer: 2,
        funFact: "Baby flamingos are born gray and turn pink from eating shrimp and algae!",
      },
      {
        id: "a254",
        question: "Why do flamingos stand on one leg?",
        options: ["To conserve heat", "To rest", "Better balance", "All of the above"],
        correctAnswer: 3,
        funFact: "Standing on one leg helps flamingos conserve body heat and rest their muscles!",
      },
      {
        id: "a255",
        question: "How long can flamingos live?",
        options: ["10-15 years", "20-30 years", "40-60 years", "80-100 years"],
        correctAnswer: 2,
        funFact: "Flamingos can live 40-60 years in the wild and even longer in captivity!",
      },
      {
        id: "a256",
        question: "What is a group of flamingos called?",
        options: ["Flock", "Flamboyance", "Colony", "All of the above"],
        correctAnswer: 3,
        funFact: "Flamingo groups can be called a flock, flamboyance, or colony!",
      },
      {
        id: "a257",
        question: "How many chambers does a cow's stomach have?",
        options: ["1", "2", "3", "4"],
        correctAnswer: 3,
        funFact: "Cows have 4 stomach chambers to help them digest grass and other tough plants!",
      },
      {
        id: "a258",
        question: "How much milk can a dairy cow produce per day?",
        options: ["2-3 gallons", "4-5 gallons", "6-7 gallons", "8-9 gallons"],
        correctAnswer: 2,
        funFact: "A good dairy cow can produce 6-7 gallons of milk per day!",
      },
      {
        id: "a259",
        question: "Cows have best friends.",
        options: ["True", "False"],
        correctAnswer: 0,
        funFact: "Cows form close friendships and become stressed when separated from their best friends!",
      },
      {
        id: "a260",
        question: "How many muscles does an elephant's trunk have?",
        options: ["10,000", "20,000", "40,000", "60,000"],
        correctAnswer: 2,
        funFact: "An elephant's trunk has over 40,000 muscles - more than in the entire human body!",
      },
      {
        id: "a261",
        question: "How much water can an elephant drink per day?",
        options: ["50 gallons", "100 gallons", "200 gallons", "300 gallons"],
        correctAnswer: 3,
        funFact: "Elephants can drink up to 300 gallons of water per day!",
      },
      {
        id: "a262",
        question: "Elephants are afraid of mice.",
        options: ["True", "False"],
        correctAnswer: 1,
        funFact: "This is a myth - elephants aren't afraid of mice, though they are cautious of small movements!",
      },
      {
        id: "a263",
        question: "How long is an elephant's pregnancy?",
        options: ["12 months", "18 months", "22 months", "24 months"],
        correctAnswer: 2,
        funFact: "Elephant pregnancies last 22 months - the longest of any mammal!",
      },
      {
        id: "a264",
        question: "What is the fastest marine animal?",
        options: ["Dolphin", "Tuna", "Sailfish", "Marlin"],
        correctAnswer: 2,
        funFact: "Sailfish can reach speeds of 68 mph, making them the fastest fish in the ocean!",
      },
      {
        id: "a265",
        question: "How many species of whales are there?",
        options: ["40", "60", "80", "100"],
        correctAnswer: 2,
        funFact: "There are approximately 80 species of whales, dolphins, and porpoises!",
      },
      {
        id: "a266",
        question: "Which whale has the largest brain?",
        options: ["Blue Whale", "Sperm Whale", "Humpback Whale", "Gray Whale"],
        correctAnswer: 1,
        funFact: "Sperm whales have the largest brain of any animal, weighing up to 17 pounds!",
      },
      {
        id: "a267",
        question: "How deep can sperm whales dive?",
        options: ["1,000 feet", "3,000 feet", "7,000 feet", "10,000 feet"],
        correctAnswer: 2,
        funFact: "Sperm whales can dive over 7,000 feet deep and hold their breath for 90 minutes!",
      },
      {
        id: "a268",
        question: "What is the largest animal that has ever lived?",
        options: ["Tyrannosaurus Rex", "Woolly Mammoth", "Blue Whale", "Megalodon"],
        correctAnswer: 2,
        funFact: "Blue whales are the largest animals ever known to exist, even bigger than dinosaurs!",
      },
      {
        id: "a269",
        question: "How much can a blue whale's heart weigh?",
        options: ["200 pounds", "400 pounds", "600 pounds", "800 pounds"],
        correctAnswer: 2,
        funFact: "A blue whale's heart can weigh 600 pounds - as much as a small car!",
      },
      {
        id: "a270",
        question: "How loud can a blue whale's call be?",
        options: ["100 decibels", "150 decibels", "188 decibels", "200 decibels"],
        correctAnswer: 2,
        funFact: "Blue whale calls can reach 188 decibels - louder than a jet engine!",
      },
    ],
  },
  {
    id: "food",
    name: "Foodie Frenzy",
    emoji: "🍕",
    description: "Deliciously weird facts about what we eat!",
    color: "from-yellow-400 to-orange-500",
    questions: [
      {
        id: "f1",
        question: "What spice is derived from the Crocus flower?",
        options: ["Paprika", "Saffron", "Turmeric", "Expensive disappointment"],
        correctAnswer: 1,
        funFact: "Saffron is worth more than gold by weight - literally liquid gold!",
      },
      {
        id: "f2",
        question: "Which fruit is technically a berry?",
        options: ["Strawberry", "Raspberry", "Banana", "My weird neighbor"],
        correctAnswer: 2,
        funFact: "Bananas are berries, but strawberries aren't. Nature is confusing!",
      },
      {
        id: "f3",
        question: 'What does "wasabi" literally translate to?',
        options: ["Green fire", "Mountain hollyhock", "Nose burner", "Regret paste"],
        correctAnswer: 1,
        funFact: 'Most "wasabi" you eat is actually just green-colored horseradish!',
      },
    ],
  },
  {
    id: "space",
    name: "Space Oddities",
    emoji: "🚀",
    description: "Out-of-this-world facts from the cosmos!",
    color: "from-purple-400 to-pink-500",
    questions: [
      {
        id: "s1",
        question: "How long is a day on Venus?",
        options: ["24 hours", "243 Earth days", "12 hours", "Longer than Monday"],
        correctAnswer: 1,
        funFact: "A day on Venus is longer than its year - talk about a long Monday!",
      },
      {
        id: "s2",
        question: "What color is the sunset on Mars?",
        options: ["Red", "Blue", "Green", "Instagram filter"],
        correctAnswer: 1,
        funFact: "Mars has blue sunsets because of how light scatters in its thin atmosphere!",
      },
      {
        id: "s3",
        question: "How many moons does Jupiter have?",
        options: ["12", "67", "95", "Too many to count"],
        correctAnswer: 2,
        funFact: "Jupiter has 95 known moons - it's like the solar system's moon collector!",
      },
    ],
  },
  {
    id: "history",
    name: "Historical Hilarity",
    emoji: "🏛️",
    description: "The past was weirder than you think!",
    color: "from-red-400 to-yellow-500",
    questions: [
      {
        id: "h1",
        question: "What did Napoleon fear most?",
        options: ["Heights", "Cats", "Water", "Bad hair days"],
        correctAnswer: 1,
        funFact: "Napoleon had ailurophobia - a fear of cats. Ironic for such a fierce leader!",
      },
      {
        id: "h2",
        question: "How long did the shortest war in history last?",
        options: ["1 hour", "38 minutes", "3 days", "My attention span"],
        correctAnswer: 1,
        funFact: "The Anglo-Zanzibar War lasted only 38-45 minutes in 1896!",
      },
      {
        id: "h3",
        question: "What was ketchup originally sold as?",
        options: ["Sauce", "Medicine", "Paint", "Liquid disappointment"],
        correctAnswer: 1,
        funFact: "Ketchup was sold as medicine in the 1830s - imagine that prescription!",
      },
    ],
  },
]

export interface Achievement {
  id: string
  name: string
  description: string
  emoji: string
  condition: (stats: GameStats) => boolean
}

export interface GameStats {
  totalScore: number
  questionsAnswered: number
  correctAnswers: number
  categoriesCompleted: string[]
  achievements: string[]
}

export const achievements: Achievement[] = [
  {
    id: "first-correct",
    name: "First Blood",
    description: "Answer your first question correctly",
    emoji: "🎯",
    condition: (stats) => stats.correctAnswers >= 1,
  },
  {
    id: "perfect-category",
    name: "Category Master",
    description: "Complete a category with 100% accuracy",
    emoji: "👑",
    condition: (stats) => stats.categoriesCompleted.length >= 1,
  },
  {
    id: "speed-demon",
    name: "Speed Demon",
    description: "Answer 10 questions correctly",
    emoji: "⚡",
    condition: (stats) => stats.correctAnswers >= 10,
  },
  {
    id: "trivia-master",
    name: "Trivia Master",
    description: "Complete all categories",
    emoji: "🏆",
    condition: (stats) => stats.categoriesCompleted.length >= categories.length,
  },
]
